// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAaFFxz6idUgXSKg2c4DWL34JOizQfQI',
    appId: '1:880920705125:android:638a96e68e938c2c4c2e8c',
    messagingSenderId: '880920705125',
    projectId: 'e-pill-9d1d5',
    storageBucket: 'e-pill-9d1d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSG-DQX7_LOLesjzjDfcw5dkLqxJIxU8',
    appId: '1:880920705125:ios:df82e44fde027a734c2e8c',
    messagingSenderId: '880920705125',
    projectId: 'e-pill-9d1d5',
    storageBucket: 'e-pill-9d1d5.appspot.com',
    androidClientId: '880920705125-4pe7ikcmerg3gk63vnjb4tt4p5h76bsk.apps.googleusercontent.com',
    iosClientId: '880920705125-78p456scktkm76u8m9ptab4h29jictgg.apps.googleusercontent.com',
    iosBundleId: 'com.halfwaydevs.ePill',
  );
}
